---
name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: ./.github/actions/go-release
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
